## Configuracion de Instancia
server:
  port: 8082
  error:
    include-stacktrace: on_param

## Configuracion de Spring
spring:
  application:
    name: ms-books-payments
  datasource:
    url: jdbc:mysql://${ENDPOINT_DB_PAYMENTS:localhost}:3307/payments
    username: ${USER_DB_PAYMENTS:usr_db_payments}
    password: ${PASS_DB_PAYMENTS:book_2025}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      poolName: UserPool
      auto-commit: false
  jpa:
    generate-ddl: false
    show-sql: true
    properties.hibernate.format_sql: true
    hibernate.ddl-auto: none

## Configuracion del cliente de Eureka
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
    hostname: ms-books-payments



## Configuracion secundaria (custom)
getBook:
  url: http://ms-books-catalogue/books/%s
## Configuracion secundaria (custom)
getUser:
  url: http://ms-books-users/users/%s